name: Push Python Package to Cloudsmith

on:
  push:
    branches:
      - master # Replace with your default branch name if different

jobs:
  push-python-package:
    name: Push Python Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cloudsmith CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/cloudsmith/cli/setup.deb.sh' | sudo -E bash
          sudo apt-get update
          sudo apt-get install -y cloudsmith

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          pip install --upgrade cloudsmith-cli
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Push to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUD_API_KEY }}
        run: |
          cloudsmith push python interview/interview-piyush-saraswat dist/*.whl --republish
