name: Push Python Package to Cloudsmith

on:
  push:
    branches:
      - master
  schedule:
    # Run every 6 hours
    - cron: '0 0,6,12,18 * * *'

jobs:
  push-python-package:
    name: Push Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cloudsmith CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/cloudsmith/cli/setup.deb.sh' | sudo -E bash
          sudo apt-get install cloudsmith-cli -y

      - name: Push to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push python interview-piyush-saraswat/cloudsmith-assessment-piyush-saraswat test/fixture/cloudsmith-python-example-1.0.0.tar.gz --republish

