name: Publish Python distributions to Cloudsmith

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 setuptools wheel

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build binary wheel and source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package to Cloudsmith
        uses: cloudsmith-io/cloudsmith-action@v1
        with:
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
          owner: 'interview-piyush-saraswat'
          repo: 'cloudsmith-assessment-piyush-saraswat'
          file: 'dist/*'

